# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Taskfile for all dead code elimination tasks
# Learn more: https://taskfile.dev

version: "3"

tasks:
  deadcode:check:
    desc: Find dead/unused code
    aliases:
      - deadcode
    cmds:
      - task: deadnix:lint:check

  deadcode:fix:
    desc: Auto-fix/remove all dead/unused code
    aliases:
      - deadcode:fix
    cmds:
      - echo "No autofixing deadcode elimination available."
